name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2

- pip:
  - scikit-learn
  - pandas
  - numpy
  - azureml-core
  - azureml-defaults
channels:
- anaconda
- conda-forge